project_name: ghcli-enhance
env:
  - GO111MODULE=on
  - CGO_ENABLED=0
before:
  hooks:
    - go mod tidy
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
builds:
  - main: .
    ldflags:
      - -s -w
      - -X github.com/qdriven/qfluent-go/cmd.Version={{.Version}}
      - -X github.com/qdriven/qfluent-go/cmd.Revision={{.ShortCommit}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: windows
        goarch: arm
release:
  name_template: "{{ .Version }} - {{ .Date }}"
  draft: true
  header: |
    [![Github Releases ({{ .Tag }})](https://img.shields.io/github/downloads/msoap/shell2http/{{ .Tag }}/total.svg)](https://github.com/msoap/shell2http/releases/latest) [![Github All Releases](https://img.shields.io/github/downloads/msoap/shell2http/total.svg)](https://github.com/msoap/shell2http/releases)
